# Generated by Django 2.2.5 on 2019-10-24 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20191024_0242'),
        ('troubleticket', '0003_auto_20191024_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroubleTicketAnomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('log_record_number', models.IntegerField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TrafficLog')),
            ],
        ),
        migrations.CreateModel(
            name='TroubleTicketFollowUpAnomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_datetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trouble_ticket_anomaly_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trouble_ticket_anomaly_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('trouble_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troubleticket.TroubleTicketAnomaly')),
            ],
        ),
    ]
